# -*- coding: utf-8 -*-
"""Super Store

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfAN7RYhTuax2FV4KC9WRRVHmcYdEvm-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from scipy import stats

path = "/content/samplesuperstore - samplesuperstore.csv"

df = pd.read_csv(path)

print(df.head())

print(df.info())

print(df.isnull().sum())

print("Average Sales:", np.mean(df["Sales"]))
sales = df.groupby("Category")["Sales"].sum()
print(sales)

plt.bar(sales.index, sales.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

sns.scatterplot(data=df, x="Sales", y="Profit")
plt.title("Sales vs Profit")
plt.show()

X_train, X_test = train_test_split(df, test_size=0.2)
print("Training Rows:", len(X_train))
print("Testing Rows:", len(X_test))

print("Mean Sales:", stats.tmean(df["Sales"]))